# -*- coding: utf-8 -*-
"""Intern_Project_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HiskMATd_aMsZAPSHzGl4IwWC_ERhrC
"""

!pip install streamlit plotly pandas numpy
!npm install localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import plotly.graph_objects as go
# 
# # ----------------------------------------
# # 1. Page Configuration
# # ----------------------------------------
# st.set_page_config(page_title="UAC Care Pipeline Analytics", layout="wide")
# 
# # ----------------------------------------
# # 2. Data Loading & Preprocessing
# # ----------------------------------------
# @st.cache_data
# def load_data():
#     df = pd.read_csv('HHS_Unaccompanied_Alien_Children_Program.csv')
#     df = df.dropna(how='all')
# 
#     # Rename for easier access
#     df.columns = ['Date', 'Intake_CBP', 'In_CBP_Custody', 'Transferred_Out_CBP', 'In_HHS_Care', 'Discharged_HHS']
# 
#     # Clean data types
#     df['In_HHS_Care'] = df['In_HHS_Care'].astype(str).str.replace(',', '').astype(float)
#     df['Date'] = pd.to_datetime(df['Date'])
# 
#     # IMPORTANT: Sort chronologically for accurate time-series and rolling calculations
#     df = df.sort_values('Date').reset_index(drop=True)
# 
#     # Calculate KPIs
#     df['Transfer_Efficiency'] = np.where(df['In_CBP_Custody'] > 0, df['Transferred_Out_CBP'] / df['In_CBP_Custody'], 0)
#     df['Discharge_Effectiveness'] = np.where(df['In_HHS_Care'] > 0, df['Discharged_HHS'] / df['In_HHS_Care'], 0)
#     df['Pipeline_Throughput'] = np.where(df['Intake_CBP'] > 0, df['Discharged_HHS'] / df['Intake_CBP'], 0)
# 
#     # New KPI: Backlog Accumulation Rate (Intake vs Discharge gap)
#     df['Backlog_Severity'] = df['Intake_CBP'] - df['Discharged_HHS']
# 
#     # New KPI: Outcome Stability Score (30-day rolling variance of discharge effectiveness)
#     # A lower standard deviation means a more stable, predictable outcome pipeline
#     df['Outcome_Stability'] = df['Discharge_Effectiveness'].rolling(window=30).std()
# 
#     return df
# 
# df = load_data()
# 
# # ----------------------------------------
# # 3. Sidebar Controls
# # ----------------------------------------
# st.sidebar.header("Dashboard Controls")
# st.sidebar.markdown("Filter the dataset to isolate specific periods of backlog or efficiency changes.")
# 
# # Date Range Slider
# min_date = df['Date'].min().date()
# max_date = df['Date'].max().date()
# start_date, end_date = st.sidebar.slider(
#     "Select Date Range",
#     min_value=min_date, max_value=max_date,
#     value=(min_date, max_date)
# )
# 
# # Filter Data
# mask = (df['Date'].dt.date >= start_date) & (df['Date'].dt.date <= end_date)
# filtered_df = df.loc[mask]
# 
# # ----------------------------------------
# # 4. Main Dashboard UI
# # ----------------------------------------
# st.title("Care Transition Efficiency & Placement Outcome Analytics")
# st.markdown("Analyzing the efficiency of the UAC pipeline from apprehension to sponsor reunification.")
# st.divider()
# 
# # --- TOP ROW: KPI Metrics ---
# st.subheader("System Health Overview (Latest 7-Day Averages)")
# col1, col2, col3, col4 = st.columns(4)
# 
# # Calculate latest metrics vs previous week for delta
# latest_7 = filtered_df.tail(7).mean(numeric_only=True)
# prev_7 = filtered_df.iloc[-14:-7].mean(numeric_only=True) if len(filtered_df) >= 14 else latest_7
# 
# with col1:
#     st.metric(label="Transfer Efficiency Ratio",
#               value=f"{latest_7['Transfer_Efficiency']:.2%}",
#               delta=f"{(latest_7['Transfer_Efficiency'] - prev_7['Transfer_Efficiency']):.2%} vs Prev Wk")
# with col2:
#     st.metric(label="Discharge Effectiveness",
#               value=f"{latest_7['Discharge_Effectiveness']:.2%}",
#               delta=f"{(latest_7['Discharge_Effectiveness'] - prev_7['Discharge_Effectiveness']):.2%} vs Prev Wk")
# with col3:
#     st.metric(label="Pipeline Throughput Rate",
#               value=f"{latest_7['Pipeline_Throughput']:.2f}",
#               delta=f"{(latest_7['Pipeline_Throughput'] - prev_7['Pipeline_Throughput']):.2f} vs Prev Wk")
# with col4:
#     backlog_delta = latest_7['Backlog_Severity'] - prev_7['Backlog_Severity']
#     # Inverse delta color because a rising backlog is bad
#     st.metric(label="Avg Daily Backlog Accumulation",
#               value=f"{latest_7['Backlog_Severity']:,.0f}",
#               delta=f"{backlog_delta:,.0f} vs Prev Wk",
#               delta_color="inverse")
# 
# st.divider()
# 
# # --- MIDDLE SECTION: Flow & Bottlenecks ---
# colA, colB = st.columns(2)
# 
# with colA:
#     st.subheader("Care Pipeline Flow Visualization")
#     fig_flow = go.Figure()
#     fig_flow.add_trace(go.Scatter(x=filtered_df['Date'], y=filtered_df['Intake_CBP'], name='Intake (CBP)', mode='lines', line=dict(color='orange')))
#     fig_flow.add_trace(go.Scatter(x=filtered_df['Date'], y=filtered_df['In_HHS_Care'], name='Active HHS Care', mode='lines', line=dict(color='blue')))
#     fig_flow.update_layout(height=400, margin=dict(l=0, r=0, t=30, b=0), legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
#     st.plotly_chart(fig_flow, use_container_width=True)
# 
# with colB:
#     st.subheader("Bottleneck Detection (Intake vs Exits Gap)")
#     # Coloring bars: Red if backlog is accumulating (Intake > Exits), Green if clearing
#     colors = ['#d62728' if val > 0 else '#2ca02c' for val in filtered_df['Backlog_Severity']]
#     fig_backlog = go.Figure(data=[go.Bar(
#         x=filtered_df['Date'],
#         y=filtered_df['Backlog_Severity'],
#         marker_color=colors,
#         name='Daily Backlog'
#     )])
#     fig_backlog.update_layout(height=400, margin=dict(l=0, r=0, t=30, b=0), yaxis_title="Unresolved Cases Accumulation")
#     st.plotly_chart(fig_backlog, use_container_width=True)
# 
# st.divider()
# 
# # --- BOTTOM SECTION: Efficiency & Stability Trends ---
# st.subheader("Process Efficiency & Outcome Stability")
# toggle_metric = st.radio("Select Metric to Analyze:",
#                          ('Transfer Efficiency (CBP -> HHS)', 'Discharge Effectiveness (HHS -> Sponsor)', 'Outcome Stability Score'),
#                          horizontal=True)
# 
# fig_trend = go.Figure()
# 
# if toggle_metric == 'Transfer Efficiency (CBP -> HHS)':
#     fig_trend.add_trace(go.Scatter(x=filtered_df['Date'], y=filtered_df['Transfer_Efficiency'].rolling(7).mean(), name='7-Day Avg', line=dict(color='#1f77b4', width=3)))
#     fig_trend.update_layout(yaxis_title="Ratio", yaxis_range=[0, 1])
# 
# elif toggle_metric == 'Discharge Effectiveness (HHS -> Sponsor)':
#     fig_trend.add_trace(go.Scatter(x=filtered_df['Date'], y=filtered_df['Discharge_Effectiveness'].rolling(7).mean(), name='7-Day Avg', line=dict(color='#ff7f0e', width=3)))
#     fig_trend.update_layout(yaxis_title="Index", yaxis_range=[0, 0.15])
# 
# else:
#     # Outcome Stability
#     fig_trend.add_trace(go.Scatter(x=filtered_df['Date'], y=filtered_df['Outcome_Stability'], fill='tozeroy', name='Volatility', line=dict(color='#9467bd')))
#     fig_trend.update_layout(yaxis_title="Standard Deviation (Lower = More Stable)")
# 
# fig_trend.update_layout(height=350, margin=dict(l=0, r=0, t=30, b=0))
# st.plotly_chart(fig_trend, use_container_width=True)

import urllib
print("Password/Endpoint IP for LocalTunnel is:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))

!streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false & npx localtunnel --port 8501

